version: '3.6'

services:
  postgres-service:
    container_name: postgres_service_bis
    image: postgres:14-alpine
    ports:
      - '5437:5437'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: on-failure
    networks:
      - default
    command: -p 5437
